import React from 'react'

//css
import classes from './Top_bar.module.css'

//components
import Vulnerability from "./Components/Vulnerability/Vulnerability"

type props = {

    active: string//the currently active button, to highlight it, also generated by the util func - generate top bar variables
}

export const Top_bar = ({ active }: props) => {

    return (

        <div className={classes.container}>

            <div className={classes.button_container}>

                {["Persisted XSS", "Reflected XSS", "Dom-based XSS", "Database injection"].map(vulnerability => <Vulnerability text={vulnerability} highlighted={vulnerability === active ? true : false}/>)}

            </div>

        </div>

    )

}

export default Top_bar